devopswroclaw/devopswroclaw

- ideas_for_presentations.md
- running_a_meetup.md
and first two items to ideas_for_presentations.md
> Added a podcast to running_a_meetup.md 

- ideas_for_presentations.md
- added ideas from Piotr Kurpik
modified:   ideas_for_presentations.md
> [kamilherbik_pkurpik]

- ideas_for_presentations.md
Version control strategies and their consequences.
Talk about version control of source code, configuration files and libraries.
> Proposed talk: Version control strategies and their consequences

- ideas_for_presentations.md
Plus rearranged the talks list
> Added new proposed talk

- ideas_for_presentations.md
- incomming presentation form OVH
modified:   ideas_for_presentations.md
> [jakub_slonimski]

- ideas_for_presentations.md
> New proposed talk

- doodle_polls.md
- DevOps Wroclaw agenda
zmodyfikowany: doodle_polls.md
> [new_poll]

- README.md
- some small corrections related to devops data
- added an Agenda for 28.06.2016
- added small description from Piotr Kurpik about his presentation
modified:   README.md
> [meetup_28062016]

- README.md
- modify README file for Piotr's presentation
modified:   README.md
> [piotr_rogala_intro]

- README.md
- devops_materials/books.md
- devops_materials/conferences.md
- devops_materials/news.md
- devops_materials/podcasts.md
- devops_materials/presentations.md
> Devops materials

- README.md
- small correction
modified:   README.md
> [28.06.2016_links_corrections]

- README.md
- Agenda and descriptions added
zmodyfikowany: README.md
> [30-08-2016]

- README.md
> Added links to presentations from 2016-08-30

- README.md
- README updated according to the content of 4th meetup
- waiting for presentation from Lukasz Hryniuk
- zmodyfikowany: README.md
> [25102016_add1]

- README.md
- presentation from Lukasz Hryniuk
- modified:   README.md
> [lhryniuk]

- devops_materials/books.md
- "The DevOps Handbook" added
- modified:   devops_materials/books.md
> [devops_handbook]

- README.md
- link to mlasyk's systemd presentation
- modified:   README.md
> [mlasyk_systemd]

- README.md
- Michal Bolek added
- some corrections
- modified:   README.md
> [february_2017]

- devops_jobs/README.md
- devops_jobs/logindex.ag.md
- new job offer from "Logindex AG"
- modified:   devops_jobs/README.md
- new file:   devops_jobs/logindex.ag.md
> [aws_devops_enginee_job]

- README.md
- README updated by 31-05-2017
modified:   README.md
> [31052017]

- ideas_for_presentations.md
- new presenters for upcoming meetup
modified:   ideas_for_presentations.md
> [meetups_drafts]

- README.md
- README file updated with the presentations which were set on January and April 2018
> [big_update]

- README.md
> Add the 2018-06 meetup

- README.md
> Add link to Tomasz Ziółkowski slides

- README.md
> [2019-02] Add meetups: 2018-09-25, 2018-11-27, 2019-02-12
